This question should be answered using the Carseats data set.

(a) Fit a multiple regression model to predict Sales using Price,
Urban, and US.

(b) Provide an interpretation of each coefcient in the model. Be
careful—some of the variables in the model are qualitative!

(c) Write out the model in equation form, being careful to handle
the qualitative variables properly.

(d) For which of the predictors can you reject the null hypothesis
H0 : βj = 0?

(e) On the basis of your response to the previous question, ft a
smaller model that only uses the predictors for which there is
evidence of association with the outcome.

(f) How well do the models in (a) and (e) ft the data?

(g) Using the model from (e), obtain 95 % confdence intervals for
the coefcient(s).

(h) Is there evidence of outliers or high leverage observations in the
model from (e)?

In [1]:
pip install ISLP

Requirement already satisfied: ISLP in c:\users\pytla\anaconda3\lib\site-packages (0.4.0)
Requirement already satisfied: numpy>=1.7.1 in c:\users\pytla\anaconda3\lib\site-packages (from ISLP) (2.1.3)
Requirement already satisfied: scipy>=0.9 in c:\users\pytla\anaconda3\lib\site-packages (from ISLP) (1.15.3)
Requirement already satisfied: pandas>=0.20 in c:\users\pytla\anaconda3\lib\site-packages (from ISLP) (2.2.3)
Requirement already satisfied: lxml in c:\users\pytla\anaconda3\lib\site-packages (from ISLP) (5.3.0)
Requirement already satisfied: scikit-learn>=1.2 in c:\users\pytla\anaconda3\lib\site-packages (from ISLP) (1.6.1)
Requirement already satisfied: joblib in c:\users\pytla\anaconda3\lib\site-packages (from ISLP) (1.4.2)
Requirement already satisfied: statsmodels>=0.13 in c:\users\pytla\anaconda3\lib\site-packages (from ISLP) (0.14.4)
Requirement already satisfied: lifelines in c:\users\pytla\anaconda3\lib\site-packages (from ISLP) (0.30.0)
Requirement already satisfied: pygam in c:\users\pytla\anaconda3\lib\site-packages (from ISLP) (0.10.1)
Requirement already satisfied: torch in c:\users\pytla\anaconda3\lib\site-packages (from ISLP) (2.8.0)
Requirement already satisfied: pytorch-lightning in c:\users\pytla\anaconda3\lib\site-packages (from ISLP) (2.5.5)
Requirement already satisfied: torchmetrics in c:\users\pytla\anaconda3\lib\site-packages (from ISLP) (1.8.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pytla\anaconda3\lib\site-packages (from pandas>=0.20->ISLP) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pytla\anaconda3\lib\site-packages (from pandas>=0.20->ISLP) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pytla\anaconda3\lib\site-packages (from pandas>=0.20->ISLP) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\pytla\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.20->ISLP) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\pytla\anaconda3\lib\site-packages (from scikit-learn>=1.2->ISLP) (3.5.0)
Requirement already satisfied: patsy>=0.5.6 in c:\users\pytla\anaconda3\lib\site-packages (from statsmodels>=0.13->ISLP) (1.0.1)
Requirement already satisfied: packaging>=21.3 in c:\users\pytla\anaconda3\lib\site-packages (from statsmodels>=0.13->ISLP) (24.2)
Requirement already satisfied: matplotlib>=3.0 in c:\users\pytla\anaconda3\lib\site-packages (from lifelines->ISLP) (3.10.0)
Requirement already satisfied: autograd>=1.5 in c:\users\pytla\anaconda3\lib\site-packages (from lifelines->ISLP) (1.8.0)
Requirement already satisfied: autograd-gamma>=0.3 in c:\users\pytla\anaconda3\lib\site-packages (from lifelines->ISLP) (0.5.0)
Requirement already satisfied: formulaic>=0.2.2 in c:\users\pytla\anaconda3\lib\site-packages (from lifelines->ISLP) (1.2.1)
Requirement already satisfied: interface-meta>=1.2.0 in c:\users\pytla\anaconda3\lib\site-packages (from formulaic>=0.2.2->lifelines->ISLP) (1.3.0)
Requirement already satisfied: narwhals>=1.17 in c:\users\pytla\anaconda3\lib\site-packages (from formulaic>=0.2.2->lifelines->ISLP) (1.31.0)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\pytla\anaconda3\lib\site-packages (from formulaic>=0.2.2->lifelines->ISLP) (4.12.2)
Requirement already satisfied: wrapt>=1.17.0rc1 in c:\users\pytla\anaconda3\lib\site-packages (from formulaic>=0.2.2->lifelines->ISLP) (1.17.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\pytla\anaconda3\lib\site-packages (from matplotlib>=3.0->lifelines->ISLP) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\pytla\anaconda3\lib\site-packages (from matplotlib>=3.0->lifelines->ISLP) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\pytla\anaconda3\lib\site-packages (from matplotlib>=3.0->lifelines->ISLP) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\pytla\anaconda3\lib\site-packages (from matplotlib>=3.0->lifelines->ISLP) (1.4.8)
Requirement already satisfied: pillow>=8 in c:\users\pytla\anaconda3\lib\site-packages (from matplotlib>=3.0->lifelines->ISLP) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\pytla\anaconda3\lib\site-packages (from matplotlib>=3.0->lifelines->ISLP) (3.2.0)
Requirement already satisfied: progressbar2<5,>=4.2.0 in c:\users\pytla\anaconda3\lib\site-packages (from pygam->ISLP) (4.5.0)
Requirement already satisfied: python-utils>=3.8.1 in c:\users\pytla\anaconda3\lib\site-packages (from progressbar2<5,>=4.2.0->pygam->ISLP) (3.9.1)
Requirement already satisfied: tqdm>=4.57.0 in c:\users\pytla\anaconda3\lib\site-packages (from pytorch-lightning->ISLP) (4.67.1)
Requirement already satisfied: PyYAML>5.4 in c:\users\pytla\anaconda3\lib\site-packages (from pytorch-lightning->ISLP) (6.0.2)
Requirement already satisfied: fsspec>=2022.5.0 in c:\users\pytla\anaconda3\lib\site-packages (from fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (2025.3.2)
Requirement already satisfied: lightning-utilities>=0.10.0 in c:\users\pytla\anaconda3\lib\site-packages (from pytorch-lightning->ISLP) (0.15.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\pytla\anaconda3\lib\site-packages (from fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (3.11.10)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\pytla\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\pytla\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\pytla\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\pytla\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\pytla\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\pytla\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\pytla\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (1.18.0)
Requirement already satisfied: idna>=2.0 in c:\users\pytla\anaconda3\lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning->ISLP) (3.7)
Requirement already satisfied: setuptools in c:\users\pytla\anaconda3\lib\site-packages (from lightning-utilities>=0.10.0->pytorch-lightning->ISLP) (72.1.0)
Requirement already satisfied: filelock in c:\users\pytla\anaconda3\lib\site-packages (from torch->ISLP) (3.17.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\pytla\anaconda3\lib\site-packages (from torch->ISLP) (1.13.3)
Requirement already satisfied: networkx in c:\users\pytla\anaconda3\lib\site-packages (from torch->ISLP) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\pytla\anaconda3\lib\site-packages (from torch->ISLP) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\pytla\anaconda3\lib\site-packages (from sympy>=1.13.3->torch->ISLP) (1.3.0)
Requirement already satisfied: colorama in c:\users\pytla\anaconda3\lib\site-packages (from tqdm>=4.57.0->pytorch-lightning->ISLP) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\pytla\anaconda3\lib\site-packages (from jinja2->torch->ISLP) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf

from statsmodels.stats.anova import anova_lm
from ISLP.models import summarize, poly
from ISLP.models import ModelSpec as MS
from ISLP import load_data

In [3]:
df = load_data("Carseats")

In [4]:
df.dropna()
df

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,9.50,138,73,11,276,120,Bad,42,17,Yes,Yes
1,11.22,111,48,16,260,83,Good,65,10,Yes,Yes
2,10.06,113,35,10,269,80,Medium,59,12,Yes,Yes
3,7.40,117,100,4,466,97,Medium,55,14,Yes,Yes
4,4.15,141,64,3,340,128,Bad,38,13,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...
395,12.57,138,108,17,203,128,Good,33,14,Yes,Yes
396,6.14,139,23,3,37,120,Medium,55,11,No,Yes
397,7.41,162,26,12,368,159,Medium,40,18,Yes,Yes
398,5.94,100,79,7,284,95,Bad,50,12,Yes,Yes
399,9.71,134,37,0,27,120,Good,49,16,Yes,Yes

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sales        400 non-null    float64
 1   CompPrice    400 non-null    int64
 2   Income       400 non-null    int64
 3   Advertising  400 non-null    int64
 4   Population   400 non-null    int64
 5   Price        400 non-null    int64
 6   ShelveLoc    400 non-null    category
 7   Age          400 non-null    int64
 8   Education    400 non-null    int64
 9   Urban        400 non-null    category
 10  US           400 non-null    category
dtypes: category(3), float64(1), int64(7)
memory usage: 26.7 KB

(a) Fit a multiple regression model to predict Sales using Price, Urban, and US.

(b) Provide an interpretation of each coefcient in the model. Be careful—some of the variables in the model are qualitative!

In [6]:
X = df[["Price", "Urban", "US"]]
Y = df["Sales"]

mod = smf.ols("Sales ~ Price + Urban + US", data=df)
res = mod.fit()

res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.239
Model:                            OLS   Adj. R-squared:                  0.234
Method:                 Least Squares   F-statistic:                     41.52
Date:                Tue, 28 Oct 2025   Prob (F-statistic):           2.39e-23
Time:                        11:25:59   Log-Likelihood:                -927.66
No. Observations:                 400   AIC:                             1863.
Df Residuals:                     396   BIC:                             1879.
Df Model:                           3
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       13.0435      0.651     20.036      0.000      11.764      14.323
Urban[T.Yes]    -0.0219      0.272     -0.081      0.936      -0.556       0.512
US[T.Yes]        1.2006      0.259      4.635      0.000       0.691       1.710
Price           -0.0545      0.005    -10.389      0.000      -0.065      -0.044
==============================================================================
Omnibus:                        0.676   Durbin-Watson:                   1.912
Prob(Omnibus):                  0.713   Jarque-Bera (JB):                0.758
Skew:                           0.093   Prob(JB):                        0.684
Kurtosis:                       2.897   Cond. No.                         628.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Sklep w miescie ma srednie nizsza sprzedaz (o coef), p bardzo wysokie, ale nie ma dowodow
US Yes -> Sklepy w usa maja srednio 1.2 WYZSZA sprzedac, potwierdza to bardzo niskie P
Price -> kazdy dolar w cenie produktu obniza sprzedaz ....





(c) Write out the model in equation form, being careful to handle the qualitative variables properly.

(d) For which of the predictors can you reject the null hypothesis H0 : βj = 0?

(e) On the basis of your response to the previous question, ft a smaller model that only uses the predictors for which there is evidence of association with the outcome.

(f) How well do the models in (a) and (e) ft the data?

(g) Using the model from (e), obtain 95 % confdence intervals for the coefcient(s).

(h) Is there evidence of outliers or high leverage observations in the model from (e)?

c)Sales= 13.0435 − 0.0545⋅Price − 0.0219⋅Urban +1.2006⋅US
d) for US and Price due to low P
e)

In [7]:
small_md = smf.ols("Sales ~ Price + US", data=df).fit()

small_md.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.239
Model:                            OLS   Adj. R-squared:                  0.235
Method:                 Least Squares   F-statistic:                     62.43
Date:                Tue, 28 Oct 2025   Prob (F-statistic):           2.66e-24
Time:                        11:25:59   Log-Likelihood:                -927.66
No. Observations:                 400   AIC:                             1861.
Df Residuals:                     397   BIC:                             1873.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     13.0308      0.631     20.652      0.000      11.790      14.271
US[T.Yes]      1.1996      0.258      4.641      0.000       0.692       1.708
Price         -0.0545      0.005    -10.416      0.000      -0.065      -0.044
==============================================================================
Omnibus:                        0.666   Durbin-Watson:                   1.912
Prob(Omnibus):                  0.717   Jarque-Bera (JB):                0.749
Skew:                           0.092   Prob(JB):                        0.688
Kurtosis:                       2.895   Cond. No.                         607.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [10]:
small_md.conf_int(alpha=0.05)

                  0          1
Intercept  11.79032  14.271265
US[T.Yes]   0.69152   1.707766
Price      -0.06476  -0.044195